spring.application.name=ei102725gbgs

# Database Configuration
# spring.datasource.url=
# spring.datasource.username=
# spring.datasource.password=
# spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pool Settings
# spring.datasource.hikari.maximum-pool-size=10
# spring.datasource.hikari.minimum-idle=5
